#!/usr/bin/env bash

set -euo pipefail

cd -P -- "$(dirname -- "$0")"

output="${1:-dist/conf-docs-out.html}"

npm run build
npm run inline

## html-inline fails on resolving links
## there is no way to turn it off either
## so we have to do this in a hack-ish way
sed 's/<!--INJECT_FONT_LINK_HERE-->/<link rel="stylesheet" href="https:\/\/fonts.googleapis.com\/css?family=Roboto:100,300,400,500,700,900"\/>/' dist/conf-docs.html > $output

echo "built $output"
