#!/usr/bin/env bash

set -euo pipefail

cd -P -- "$(dirname -- "$0")"

output="${OUTPUT_FILE:-dist/conf-docs-out.html}"
version="$(jq -r '.version' package.json)"

npm run build
npm run inline

# Fix for macOS BSD sed
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS version
    sed -i '' "s/VERSION/$version/" dist/conf-docs.html
    sed -i '' 's/<!--INJECT_FONT_LINK_HERE-->/<link rel="stylesheet" href="https:\/\/fonts.googleapis.com\/css?family=Roboto:100,300,400,500,700,900"\/>/' dist/conf-docs.html > $output
else
    # Linux version
    sed -i "s/VERSION/$version/" dist/conf-docs.html
    sed 's/<!--INJECT_FONT_LINK_HERE-->/<link rel="stylesheet" href="https:\/\/fonts.googleapis.com\/css?family=Roboto:100,300,400,500,700,900"\/>/' dist/conf-docs.html > $output
fi

echo "built $output"
